public class Person {
public String name;
private String hairColor;
private int age;
private double height;

public Person() {
age = 16;
name = Emmer Checkers; 
height = 6.5; 
hairColor = bright purple;
}

public void setAge(int newAge){
  age = newAge;
}

public void setName(String newName){
  name = newName;
}

public void setHeight(double newHeight){
  height = newHeight;
}

public void setHairColor(String newHairColor){
  hairColor = newHairColor;
}




}
